/**
 * lib/facebook.ts — Meta (Facebook) SDK wrapper
 *
 * Purpose: App Events only — lets Meta Ads attribute installs/conversions and
 * optimise delivery. NO Facebook Login UI.
 *
 * ATT-aware: advertiser tracking + advertiser-ID collection are gated on the
 * user's iOS App Tracking Transparency choice. We call
 * Settings.setAdvertiserTrackingEnabled(granted) BEFORE Settings.initializeSDK()
 * so the very first events respect the user's choice (Meta AEM / SKAdNetwork
 * relies on this on iOS 14.5+).
 *
 * Native wiring (App ID, Client Token, FacebookActivity, CustomTabActivity,
 * URL scheme) is generated by the `react-native-fbsdk-next` Expo config plugin
 * in app.json during prebuild — we never hand-edit native files.
 *
 * Usage:
 *   1. initFacebook(isTrackingAllowed) once on app mount, AFTER ATT resolves
 *      (app/(app)/_layout.tsx, alongside AppsFlyer).
 *   2. setFacebookUserId(userId) after sign-in (advanced matching); clear on sign-out.
 *   3. logFacebookEvent / logFacebookPurchase for key conversions.
 *
 * Dashboard note: verify events in Meta Events Manager → Test Events with a
 * RELEASE build (Events Manager → your app → Test Events → add device).
 */

import { Platform } from 'react-native';

// Lazy-load the native module — it is absent in Expo Go (requires a native
// build via `expo run:ios` / `run:android`). Mirrors lib/appsflyer.ts.
let Settings: any = null;
let AppEventsLogger: any = null;
try {
  const mod = require('react-native-fbsdk-next');
  Settings = mod?.Settings ?? null;
  AppEventsLogger = mod?.AppEventsLogger ?? null;
  if (typeof Settings?.initializeSDK !== 'function') {
    Settings = null;
    AppEventsLogger = null;
    if (__DEV__) console.warn('[Facebook] Module loaded but Settings.initializeSDK not found — check react-native-fbsdk-next version');
  } else if (__DEV__) {
    console.log('[Facebook] module loaded successfully ✓');
  }
} catch (e: any) {
  console.warn('[Facebook] require failed:', e?.message ?? e);
  Settings = null;
  AppEventsLogger = null;
}

let initialized = false;

// ─── Initialize ────────────────────────────────────────────────────────────────

/**
 * Initialize the Meta SDK. Call ONCE on app mount, after the ATT dialog resolves.
 *
 * @param isTrackingAllowed - Result of the iOS ATT prompt. On Android this is
 *   always true (ATT is iOS-only). Controls advertiser tracking + IDFA collection.
 */
export function initFacebook(isTrackingAllowed: boolean): void {
  if (!Settings) {
    if (__DEV__) console.warn('[Facebook] Native module not available — run a native build (npx expo run:ios), not Expo Go.');
    return;
  }
  if (initialized) {
    // ATT can resolve again later — keep the flag in sync without re-initing.
    // eslint-disable-next-line no-empty
    try { Settings.setAdvertiserTrackingEnabled(isTrackingAllowed); } catch {}
    return;
  }

  try {
    // ── Order matters: set advertiser tracking BEFORE initializeSDK ──────────
    // On iOS 14.5+ this is what makes the SDK ATT-compliant and feeds Meta's
    // Aggregated Event Measurement (AEM). On Android these are no-ops / harmless.
    Settings.setAdvertiserTrackingEnabled(isTrackingAllowed);
    Settings.setAdvertiserIDCollectionEnabled(isTrackingAllowed);

    // Auto-log standard app events (install, session) once initialized.
    Settings.setAutoLogAppEventsEnabled(true);

    // Boot the SDK (isAutoInitEnabled is false in the config plugin so the SDK
    // waits for this call — guaranteeing the ATE flag above is set first).
    Settings.initializeSDK();

    initialized = true;
    if (__DEV__) console.log(`[Facebook] SDK initialized ✓ | tracking allowed: ${isTrackingAllowed} | platform: ${Platform.OS}`);
  } catch (e: any) {
    if (__DEV__) console.warn('[Facebook] init failed:', e?.message ?? e);
  }
}

// ─── User identification (Advanced Matching) ────────────────────────────────────

/**
 * Associate Meta events with your Supabase user ID for advanced matching.
 * Call after successful sign-in / sign-up.
 */
export function setFacebookUserId(userId: string): void {
  if (!AppEventsLogger || !userId) return;
  // eslint-disable-next-line no-empty
  try { AppEventsLogger.setUserID(userId); } catch {}
}

/** Clear the Meta user ID on sign-out. */
export function clearFacebookUserId(): void {
  if (!AppEventsLogger) return;
  // eslint-disable-next-line no-empty
  try { AppEventsLogger.setUserID(null); } catch {}
}

/**
 * Get the Meta anonymous ID. Used to link RevenueCat → Meta so RC-forwarded
 * purchases can be matched to the same anonymous user. Null if SDK not ready.
 */
export async function getFacebookAnonymousId(): Promise<string | null> {
  if (typeof AppEventsLogger?.getAnonymousID !== 'function') return null;
  try {
    const id = await AppEventsLogger.getAnonymousID();
    return id || null;
  } catch {
    return null;
  }
}

// ─── Event catalog ──────────────────────────────────────────────────────────
//
// Canonical Meta "standard event" names. Using the literal fb_mobile_* strings
// (rather than the native AppEvents constants, which may be undefined before the
// SDK initializes) so the catalog is stable at module-eval time — mirrors the
// AFEvent catalog in lib/appsflyer.ts. Standard names map automatically to Meta
// Ads optimisation/attribution events. Custom events use snake_case.
export const FBEvent = {
  // ── Activation ──
  REGISTRATION:       'fb_mobile_complete_registration', // account created
  ONBOARDING_DONE:    'onboarding_complete',
  FIRST_REPLY:        'first_reply_generated',           // the "aha"
  COMPLETED_TUTORIAL: 'fb_mobile_tutorial_completion',

  // ── Engagement (no $ — easiest to test) ──
  SCREENSHOT_UPLOADED: 'screenshot_uploaded',
  REPLY_GENERATED:     'reply_generated',
  REPLY_COPIED:        'reply_copied',
  VIEWED_CONTENT:      'fb_mobile_content_view',

  // ── Monetization ──
  PAYWALL_VIEWED:      'paywall_viewed',
  CHECKOUT_INITIATED:  'fb_mobile_initiated_checkout',
  ADD_PAYMENT_INFO:    'fb_mobile_add_payment_info',
  TRIAL_STARTED:       'StartTrial',
  SUBSCRIBE:           'Subscribe',
  // NOTE: actual billing → use logFacebookPurchase() (maps to fb_mobile_purchase
  // with revenue), not a plain logEvent.
} as const;

// ─── Event logging ──────────────────────────────────────────────────────────

/**
 * Log a custom / standard Meta app event.
 *
 * @param eventName   Prefer a FBEvent.* value.
 * @param params      Optional string/number parameters.
 * @param valueToSum  Optional numeric value to sum (e.g. count, score).
 */
export function logFacebookEvent(
  eventName: string,
  params: Record<string, string | number> = {},
  valueToSum?: number,
): void {
  if (!AppEventsLogger) return;
  try {
    if (typeof valueToSum === 'number') {
      AppEventsLogger.logEvent(eventName, valueToSum, params);
    } else {
      AppEventsLogger.logEvent(eventName, params);
    }
    if (__DEV__) console.log('[Facebook] Event logged:', eventName);
  } catch (e: any) {
    if (__DEV__) console.warn('[Facebook] Event log failed:', eventName, e?.message ?? e);
  }
}

/**
 * Log a purchase (maps to Meta's fb_mobile_purchase with revenue).
 * Use for confirmed billing — drives ROAS in Meta Ads.
 *
 * @param amount    Purchase amount (e.g. 9.99)
 * @param currency  ISO 4217 code (e.g. 'USD')
 * @param params    Optional extra params (e.g. { product_id })
 */
export function logFacebookPurchase(
  amount: number,
  currency: string,
  params: Record<string, string | number> = {},
): void {
  if (!AppEventsLogger) return;
  try {
    AppEventsLogger.logPurchase(amount, currency, params);
    if (__DEV__) console.log('[Facebook] Purchase logged:', amount, currency);
  } catch (e: any) {
    if (__DEV__) console.warn('[Facebook] Purchase log failed:', e?.message ?? e);
  }
}
